name: Build and Deploy Docker Image with Helm Chart Update

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # 버전 태그가 푸시될 때 동작

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 저장소 체크아웃
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Docker Buildx 설정
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Docker Hub 로그인
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 4. Docker 이미지 빌드 및 푸시
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/newdawn:${{ github.sha }}
          ${{ secrets.DOCKER_USERNAME }}/newdawn:latest

    # 5. Helm values.yaml 파일 업데이트
    - name: Update Helm Chart Image Tag
      run: |
        sed -i "s|tag: .*|tag: '${{ github.sha }}'|" Chart/newdawn/values.yaml

    # 6. 변경된 values.yaml 커밋 및 푸시
    - name: Commit and Push Helm Chart Update
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add chart/newdawn/values.yaml
        git commit -m "Update image tag to ${{ github.sha }}"
        git push origin main
